export struct Mod {
    name: string,
    author: string,
    description: string,
    version: string,
    favorites: int,
    downloads: int,
    id: int,
}

export struct ModList {mods: [Mod]}

export global AppState {
    in-out property <string> current-page: "home";
    in-out property <[string]> logs: [];
    in-out property <int> selected-mod-id: 0;
    in-out property <Mod> selected-mod;

    callback FNnavigate(string);
    callback FNselected_mod(Mod) -> Mod;

    in-out property <[ModList]> mod_list: [{
        mods: []
    }];
}
