export struct Mod {
    name: string,
    author: string,
    description: string,
    version: string,
    id: int,
}

export struct ModList {mods: [Mod]}

export global AppState {
    in-out property <string> current-page: "mods";
    in-out property <[string]> logs: [
        "Welcome to Vortex AIS",
        "Console will output necessary information for you to inform developers in case something goes wrong.",
    ];
    in-out property <int> selected-mod-id: 0;
    in-out property <Mod> selected-mod;

    callback FNnavigate(string);
    callback FNselected_mod(Mod) -> Mod;

    in-out property <[ModList]> mod_list: [{
        mods: 
        [
            {
                name: "Vortex2+2",
                author: "Inuk",
                description: "Adds multiple theme support, improved physics, improved lightning, and new games and much more!\ntest0-",
                version: "2.3.1",
                id: 1
            },
        ]
    }];
}
