import { Button } from "std-widgets.slint";
import { Sidebar } from "launcher/sidebar.slint";
import { Launcher } from "launcher/pages/launcher.slint";
import { Addons } from "launcher/pages/addons.slint";
import { AppState } from "launcher/global.slint";
export { AppState }

export component MainWindow inherits Window {
    title: "Vortex AIS";

    default-font-family: "Inter";
    default-font-weight: 400;

    preferred-width: 740px;
    preferred-height: 400px;

    background: #131313;

    Text {
        text: "Vortex AIS Launcher • v0.0.0";
        color: #3f3d42;
        font-size: 8px;
        y: 2px;
        x: self.width;
    }

    Sidebar { }

    if AppState.current-page == "home": Rectangle {
        Launcher { }
    }
    if AppState.current-page == "mods": Rectangle {
        Addons { }
    }
}